### ISSUE TITLE
raise error when run 'python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes'

### ISSUE THREAD

**Issue by harborsarah** [timbroed/HRFuser#1]
Hi,

I would like to ask, when i try to run this code, this error occurs:

raise Exception('Expecting jpg image format')
Exception: Expecting jpg image format

Which is running until like 188 'in_get_lidar_img_info'

I would like to ask if your data folder structure is same as that provided by MMDection3D.
![image](https://github.com/timbroed/HRFuser/assets/65909204/4f44ce84-7f03-41ac-89f2-cf9a6746a292)

Thanks a lot!

**Comment by qinhongmi** [comment]
I have also encountered the same problem. How did you solve it?
