### ISSUE TITLE
Config files for camera+radar modalities

### ISSUE THREAD

**Issue by kvnptl** [timbroed/HRFuser#5]
Hello,

Based on my understanding of the paper, it seems that the result table includes all possible combinations of modalities. However, I noticed that in the code base, only the C+L+R+G configuration file is available. I was wondering if it would be possible to upload the configuration files for the other modalities' combinations as well. Alternatively, could you please provide instructions on how to modify the existing config file to obtain the desired modalities' combinations?

Thanks,
K

**Comment by timbroed** [comment]
Hi K,

To adapt the configuration files, you can do the following:

For the `model`:
Adapt for the `backbone` the `mod_in_channels` and the `num_fused_modalities`. 

`mod_in_channels` should thereby be a list of the number of channels that each of the additional modalities (besides the RGB) has. for C+L+R+G it is [3, 2, 1].
`num_fused_modalities` is the number of additional modalities (besides the RGB). So it should be the len(mod_in_channels).

You also need to adapt the `train_pipeline` and the `test_pipeline` and update `data` with the new pipelines:
Remove the `LoadProjectedSensorImageFile` or `LoadGatedImageFromFile` with their corresponding `Normalize` of the sensors you do not want to load anymore. Also adapt `Collect` by removing the `keys` and `meta_keys` from the corresponding sensors.

I hope this helps you.

Best,
Tim

**Comment by kvnptl** [comment]
Hello, 

Thanks for your detailed response.

Yes, I made the changes, and it worked perfectly fine. I tested both nuScenes and DENSE.
