### ISSUE TITLE
Evaluation on COCO style metric

### ISSUE THREAD

**Issue by kvnptl** [timbroed/HRFuser#6]
Hello,

As mentioned in the paper, the DENSE dataset evaluation is done using the KITTI framework, and annotations are given in the KITTI format. Is it possible to perform an evaluation in the COCO style same as done for nuScenes? 

Please let me know.

Thanks,
K

**Comment by timbroed** [comment]
That should be possible. As the COCO evaluation directly loads the ground truth (not via the testing pipeline), you would first have to convert the KITTI style annotations from DENSE to COCO style. Also, you need to adapt the _base_ dataset config to `CocoDataset` with its corresponding evaluation.

**Comment by kvnptl** [comment]
Hello,

I have generated DENSE COCO-style annotations in JSON files and modified the base dataset configuration.

In addition, I needed to modify `mmdet/datasets/coco.py` to integrate the `crop_gt` function from the KITTI2D dataset.

It worked.

Thank you.
